name: Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: read

jobs:
  build-before-release:
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    needs: build-before-release
    permissions:
      contents: write # needed to write releases
      packages: write # needed for ghcr access
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      # Finally run the release
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
